-- PayIn 交易表
-- 用于记录用户充值交易信息

CREATE TABLE `order_payin` (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `transaction_id` varchar(64) NOT NULL COMMENT '支付系统全局交易号，对内唯一标识一笔 pay-in 交易',
  `merchant_id` varchar(64) NOT NULL COMMENT '区分不同接入方/业务线',
  `merchant_order_id` varchar(128) NOT NULL COMMENT '商户订单号',
  `payment_order_id` varchar(128) COMMENT '支付订单唯一标识',
  `merchant_api_key` varchar(128) NOT NULL COMMENT '商户API Key, 用于标识商户是哪个API key 发起的支付请求',
  `real_currency` varchar(20) NOT NULL DEFAULT 'USD' COMMENT 'ISO 4217 货币代码',
  `real_amount` double NOT NULL DEFAULT '0.00' COMMENT '实际的交易金额',
  `usd_amount` double NOT NULL DEFAULT '0.00' COMMENT '美元计价金额',
  `pay_method` varchar(32) DEFAULT NULL COMMENT 'card/token/wallet/bank_transfer/qr',
  `pay_brand` varchar(64) DEFAULT NULL COMMENT '子渠道',
  `psp` varchar(64) DEFAULT NULL COMMENT '支付平台',
  `country` varchar(50) DEFAULT NULL COMMENT '国家编码',
  `channel_order_id` varchar(128) DEFAULT NULL COMMENT 'PSP/渠道返回订单号',
  `merchant_user_id` varchar(64) DEFAULT NULL COMMENT '商户用户ID',
  `status` varchar(32) NOT NULL DEFAULT 'created' COMMENT '支付状态：created, processing, success, failed',
  `failure_code` varchar(32) DEFAULT NULL COMMENT '内部错误码，便于排查',
  `failure_msg` text DEFAULT NULL COMMENT '用于客服/运营查看的失败原因',
  `psp_code` varchar(64) DEFAULT NULL COMMENT '渠道错误码，渠道返回',
  `psp_msg` text DEFAULT NULL COMMENT '渠道返回错误信息',
  `notify_url` text DEFAULT NULL COMMENT '商户回调URL',
  `return_url` text DEFAULT NULL COMMENT '商户跳转地址URL',
  `payment_url` text DEFAULT NULL COMMENT '商户跳转地址URL',
  `extra` json DEFAULT NULL COMMENT 'price_id/coins/type 等强业务字段',
  `user_info` json DEFAULT NULL COMMENT '支付商户端相关用户信息',
  `description` varchar(256) DEFAULT NULL COMMENT '支付描述，用于支付页面展示',
  `terminal_type` varchar(32) DEFAULT NULL COMMENT '终端类型',
  `token` varchar(255) DEFAULT NULL COMMENT 'token/USDT地址',
  `mark` varchar(512) DEFAULT NULL COMMENT '备注字段',
  `refund_at` int UNSIGNED NOT NULL DEFAULT '0' COMMENT '退款时间',
  `fail_at` int UNSIGNED NOT NULL DEFAULT '0' COMMENT '失败时间 支付系统确认支付失败的时间',
  `confirm_at` int UNSIGNED NOT NULL DEFAULT '0' COMMENT '确认时间 与渠道交互成功的时间',
  `success_at` int UNSIGNED NOT NULL DEFAULT '0' COMMENT '成功时间 支付系统确认支付成功的时间',
  `created_at` int UNSIGNED NOT NULL COMMENT '创建时间戳',
  `updated_at` int UNSIGNED NOT NULL COMMENT '更新时间戳',
  `expire_at` int UNSIGNED NOT NULL DEFAULT '0' COMMENT '过期时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_transaction_id` (`transaction_id`),
  KEY `idx_merchant_order_id` (`merchant_order_id`),
  KEY `idx_channel_order_id` (`channel_order_id`),
  KEY `idx_payment_order_id` (`payment_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='PayIn 交易表';
